### PR TITLE
Add missing support for additional elements/containers

### PR DESCRIPTION
**Pull request by brenner-company**
As mentioned within https://github.com/josemarluedke/ember-focus-trap/issues/71: adding support for additional elements/containers.

### CODE REVIEW

**Review by josemarluedke — APPROVED** [review]

**Review by josemarluedke — CHANGES_REQUESTED** [review]
Tests are failing, can you take a look at these?

**Comment by brenner-company** [comment]
> Tests are failing, can you take a look at these?

Weirdly enough, I got no errors when testing locally. I'll check it out 👍

**Comment by brenner-company** [comment]
> Weirdly enough, I got no errors when testing locally. 

Nevermind that, that was an error on my side.

> I'll check it out 👍

Found the issue that caused the failing test: single elements can't be ecapsulated by an array. Also added a new test that covers modifier activation with additional elements.

**Comment by brenner-company** [comment]
@josemarluedke Did you, by any chance, found the time yet to review the new changes? It would be most helpful to continue our work. Thanks!

**Comment by josemarluedke** [comment]
@brenner-company Released in v1.0.2. Sorry for the delay.

**Comment by brenner-company** [comment]
@josemarluedke No problem, thank you for putting out a new release!

**Pull request merged**
